apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Set to your required access mode 
  resources:
    requests:
      storage: 1Gi  # Adjust the size based on your storage needs
