apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyway-attestation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flyway-attestation
  template:
    metadata:
      labels:
        app: flyway-attestation
    spec:
      containers:
        - name: flyway-attestation
          image: quay.apps.ocphubho.neoleap.com.sa/ocpuat_softpos-sbs-sit/flyway/flyway:latest
          command:
            - /flyway/flyway
            - -url=jdbc:oracle:thin:@//192.168.100.52:1521/softpossbs_db_sit
            - -schemas=ATTESTATION
            - -user=ATTESTATION
            - -password=Oiu#02918#shdt9x
            - -connectRetries=10
            - -baselineOnMigrate=true
            - -createSchemas=false
            - migrate
          volumeMounts:
            - name: flywayattestation-config
              mountPath: /flyway/sql
      volumes:
        - name: flywayattestation-config
          configMap:
            name: flywayattestation-config  # Reference the ConfigMap for SQL files
