apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  annotations:
    argocd-image-updater.argoproj.io/image-list: hesh3am/myapp
    argocd-image-updater.argoproj.io/hesh3am-myapp.update-strategy: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: hesh3am/myapp:1.0  # This will be updated automatically
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
