apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      # securityContext:
      #  fsGroup: 1000
      #initContainers:
      #  - name: fix-erlang-cookie-permissions
      #    image: busybox
      #    command: ['sh', '-c', 'chmod 600 /var/lib/rabbitmq/.erlang.cookie']
      #    volumeMounts:
      #      - name: rabbitmq-data
      #        mountPath: /var/lib/rabbitmq
      #    securityContext:
      #      runAsUser: 0  # Run as root user
      containers:
        - name: rabbitmq
          image: rabbitmq:3.10-management-alpine
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: RABBITMQ_DEFAULT_PASS
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc  # Referencing the PVC here
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: client
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP

