apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant-admin
  labels:
    app: merchant-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merchant-admin
  template:
    metadata:
      labels:
        app: merchant-admin
    spec:
      serviceAccountName: softpos-anyuid
      containers:
      - name: merchant-admin
        image: quay.apps.ocphubho.neoleap.com.sa/ocpuat_softpos-sbs-sit/merchant-uat:2.2.6
        securityContext:
          runAsUser: 1  # Ensure NGINX runs as a non-root user
          runAsGroup: 1
          allowPrivilegeEscalation: true
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: merchant-admin-service
  labels:
    app: merchant-admin
spec:
  selector:
    app: merchant-admin
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 80
  type: ClusterIP # Use ClusterIP or NodePort depending on cluster capabilities