apiVersion: apps/v1
kind: Deployment
metadata:
  name: softpos-core-service
  labels:
    app: softpos-core-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: softpos-core-service
  template:
    metadata:
      labels:
        app: softpos-core-service
    spec:
      containers:
        - name: softpos-core-service
          image: quay.apps.ocphubho.neoleap.com.sa/ocpuat_softpos-sbs-sit/softpos-core-service:2.2.5-SNAPSHOT
          ports:
            - containerPort: 8084
          env:
          - name: spring.jpa.properties.hibernate.default_schema
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: TRANSACTIONS_DB_USERNAME
          - name: VAULT_TOKEN
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: VAULT_TOKEN
          - name: VAULT_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: VAULT_ADDRESS
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: ACTIVE_PROFILES
          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: TRANSACTIONS_DB_URL
          - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_DRIVER_CLASS
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: TRANSACTIONS_DB_USERNAME
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: TRANSACTIONS_DB_PASSWORD
          - name: SPRING_JPA_SHOW_SQL
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: HIBERNATE_SHOW_SQL
          - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: HIBERNATE_FORMAT_SQL
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: HIBERNATE_DDL_AUTO
          - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: HIBERNATE_DIALECT
          - name: JPOS_COMPENSATION_SERVICE
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: TRANSACTION_SERVICE_HOST
          - name: TRANSACTION_SERVICE_HOST
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: TRANSACTION_SERVICE_HOST
          - name: MERCHANT_SERVICE_HOST
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: MERCHANT_SERVICE_HOST
          - name: KEY_MANAGEMENT_SERVICE_HOST
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: KEY_MANAGEMENT_SERVICE_HOST
          - name: SECURITY_SERVICE_HOST
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: SECURITY_SERVICE_HOST
          - name: ATTESTATION_MONITORING_SERVICE_HOST
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: ATTESTATION_MONITORING_SERVICE_HOST
          - name: MANAGEMENT_PLAN_SCHEDULER_URL
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: MANAGEMENT_PLAN_SCHEDULER_URL
          - name: JAEGER_HOST
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: JAEGER_HOST
          - name: ISO_PACKAGER_XML_PATH
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: ISO_PACKAGER_XML_PATH
          - name: SIMULATOR_TOGGLER
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: SIMULATOR_TOGGLER
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: RABBITMQ_HOST
          - name: RABBITMQ_PORT
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: RABBITMQ_PORT
          - name: SYSTEM_DATE_TIME_FORMAT
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: SYSTEM_DATE_TIME_FORMAT
          # - name: RECONCILIATION_CRON_EXPRESSION
          #   valueFrom:
          #     configMapKeyRef:
          #       name: my-configmap
          #       key: RECONCILIATION_CRON_EXPRESSION
          - name: ACTIONS_CRON_EXPRESSION
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: ACTIONS_CRON_EXPRESSION
          - name: ISO_PACKAGER_VERSION
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: ISO_PACKAGER_VERSION
          - name: MONGO_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: MONGO_DB_HOST
          - name: MONGO_DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: MONGO_DB_DATABASE
          - name: MONGO_DB_PORT
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: MONGO_DB_PORT
          - name: MONGO_DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: MONGO_DB_USERNAME
          - name: MONGO_DB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: MONGO_DB_PASSWORD
          - name: MADA_TMS2_MOCK_SERVICE_HOST
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: MADA_TMS2_MOCK_SERVICE_HOST
          - name: SECURITY_PROFILE
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: SECURITY_PROFILE
          - name: CACHE_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: CACHE_DB_NAME
          - name: CACHE_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: CACHE_DB_HOST
          - name: CACHE_DB_PORT
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: CACHE_DB_PORT
          - name: PRIVATE_KEY
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: PRIVATE_KEY
          - name: PRIVATE_KEY_EXPONENT
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: PRIVATE_KEY_EXPONENT
          - name: PUBLIC_KEY_EXPONENT
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: PUBLIC_KEY_EXPONENT
          - name: Q2_SERVER_DEPLOY_DIR
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: Q2_SERVER_DEPLOY_DIR
          - name: THREAD_POOL
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: THREAD_POOL
          - name: DUMMY_SERVER_DEPLOY_DIR
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DUMMY_SERVER_DEPLOY_DIR
          - name: RECONCILIATION_CRON_EXPRESSION
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: RECONCILIATION_CRON_EXPRESSION

          # - name: RECONCILIATION_CRON_EXPRESSION
          #   value: "0 0/1 * * * *"

# #new update
          - name: DB_TYPE
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_TYPE
          - name: DB_CONNECTION_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_CONNECTION_TIMEOUT
          - name: DB_MINIMUM_IDLE
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_MINIMUM_IDLE
          - name: DB_MAXIMUM_POOL_SIZE
            valueFrom:
              configMapKeyRef:
                  name: my-configmap
                  key: DB_MAXIMUM_POOL_SIZE
          - name: DB_IDLE_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_IDLE_TIMEOUT
          - name: DB_MAX_LIFETIME
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_MAX_LIFETIME
          - name: DB_AUTO_COMMIT
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_AUTO_COMMIT
          - name: DB_VALIDATION_TIMEOUT
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_VALIDATION_TIMEOUT
          - name: DB_LEAK_DETECTION_THRESHOLD
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_LEAK_DETECTION_THRESHOLD
          - name: DB_CACHE_PREP_STMTS
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_CACHE_PREP_STMTS
                  #- name: DB_JDBC_READ_TIMEOUT
                  #valueFrom:
                  #configMapKeyRef:
                  #name: my-configmap
                  #key: DB_JDBC_READ_TIMEOUT
          - name: DB_PREP_STMT_CACHE_SIZE
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_PREP_STMT_CACHE_SIZE
          - name: DB_PREP_STMT_CACHE_SQL_LIMIT
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_PREP_STMT_CACHE_SQL_LIMIT
          - name: DB_USE_LOCAL_SESSION_STATE
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_USE_LOCAL_SESSION_STATE
          - name: DB_REWRITE_BATCHED_STATEMENTS
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_REWRITE_BATCHED_STATEMENTS
          - name: DB_CACHE_RESULT_SET_METADATA
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_CACHE_RESULT_SET_METADATA
          - name: DB_CACHE_SERVER_CONFIGURATION
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_CACHE_SERVER_CONFIGURATION
          - name: DB_ELIDE_SET_AUTO_COMMITS
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_ELIDE_SET_AUTO_COMMITS
          - name: DB_MAINTAIN_TIME_STATS
            valueFrom:
              configMapKeyRef:
                name: my-configmap
                key: DB_MAINTAIN_TIME_STATS

---
apiVersion: v1
kind: Service
metadata:
  name: softpos-core-service
spec:
  type: NodePort
  ports:
    - port: 8084
      targetPort: 8084
      # nodePort: 30084  # Change this port as needed
  selector:
    app: softpos-core-service
