apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tms-service
  template:
    metadata:
      labels:
        app: tms-service
    spec:
      containers:
      - name: tms-service
        image: quay.apps.ocphubho.neoleap.com.sa/ocpuat_softpos-sbs-sit/tms-service:2.2.5-SNAPSHOT
        ports:
        - containerPort: 8060
        env:
        - name: spring.jpa.properties.hibernate.default_schema
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: MERCHANT_DB_USERNAME 
        - name: CACHE_DB_NAME
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: CACHE_DB_NAME
        - name: CACHE_DB_HOST
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: CACHE_DB_HOST
        - name: CACHE_DB_PORT
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: CACHE_DB_PORT  
        - name: VAULT_TOKEN
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: VAULT_TOKEN
        - name: VAULT_ADDRESS
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: VAULT_ADDRESS
        - name: spring.datasource.url
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: MERCHANT_DB_URL
        - name: spring.datasource.username
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: MERCHANT_DB_USERNAME
        - name: spring.datasource.password
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: MERCHANT_DB_PASSWORD
        - name: spring.datasource.driver-class-name
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_DRIVER_CLASS
        - name: spring.jpa.show-sql
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: HIBERNATE_SHOW_SQL
        - name: spring.jpa.properties.hibernate.format_sql
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: HIBERNATE_FORMAT_SQL
        - name: spring.jpa.properties.hibernate.enable_lazy_load_no_trans
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: HIBERNATE_ENABLE_LAZY_LOAD
        - name: spring.jpa.hibernate.ddl-auto
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: HIBERNATE_DDL_AUTO
        - name: spring.jpa.properties.hibernate.dialect
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: HIBERNATE_DIALECT
        - name: JAEGER_HOST
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: JAEGER_HOST
        - name: TRIAL_NUMBER
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: TRIAL_NUMBER
        - name: IDENTITY_PROVIDER_ACCOUNT_SID
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: IDENTITY_PROVIDER_ACCOUNT_SID
        - name: IDENTITY_PROVIDER_AUTH_TOKEN
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: IDENTITY_PROVIDER_AUTH_TOKEN
        - name: IDENTITY_PROVIDER_REALM
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: IDENTITY_PROVIDER_REALM
        - name: IDENTITY_PROVIDER_CLIENT
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: IDENTITY_PROVIDER_CLIENT

        - name: IDENTITY_PROVIDER_CLIENT_SECRET
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: IDENTITY_PROVIDER_CLIENT_SECRET

        - name: IDENTITY_PROVIDER_URL
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: IDENTITY_PROVIDER_URL

        - name: IDENTITY_PROVIDER_GRANT_TYPE
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: IDENTITY_PROVIDER_GRANT_TYPE

        - name: IDENTITY_PROVIDER_LOGOUT_URL
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: IDENTITY_PROVIDER_LOGOUT_URL

        - name: IDENTITY_PROVIDER_SUPER_ADMIN_EMAIL
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: IDENTITY_PROVIDER_SUPER_ADMIN_EMAIL

        - name: IDENTITY_PROVIDER_SUPER_ADMIN_PASSWORD
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: IDENTITY_PROVIDER_SUPER_ADMIN_PASSWORD

        - name: ADMIN_PASSWORD_LENGTH
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: ADMIN_PASSWORD_LENGTH

        - name: USER_PASSWORD_LENGTH
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: USER_PASSWORD_LENGTH

        - name: TRANSACTION_SERVICE_HOST
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: TRANSACTION_SERVICE_HOST

        - name: MADA_TMS2_MOCK_SERVICE_HOST
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: MADA_TMS2_MOCK_SERVICE_HOST

        - name: SYSTEM_DATE_TIME_FORMAT
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SYSTEM_DATE_TIME_FORMAT

        - name: RABBITMQ_HOST
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: RABBITMQ_HOST

        - name: RABBITMQ_PORT
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: RABBITMQ_PORT

        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: RABBITMQ_DEFAULT_USER

        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: RABBITMQ_DEFAULT_PASS

        - name: TMS_PUBLIC_KEY_PATH
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: TMS_PUBLIC_KEY_PATH

        - name: SERVER_TMS_PRIVATE_KEY_PATH
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: SERVER_TMS_PRIVATE_KEY_PATH

        - name: IDENTITY_PROVIDER_CREDENTIALS_SECRET
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: IDENTITY_PROVIDER_CLIENT_SECRET
# #new update
        - name: DB_TYPE
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_TYPE
        - name: DB_CONNECTION_TIMEOUT
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_CONNECTION_TIMEOUT
        - name: DB_MINIMUM_IDLE
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_MINIMUM_IDLE
        - name: DB_MAXIMUM_POOL_SIZE
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_MAXIMUM_POOL_SIZE
        - name: DB_IDLE_TIMEOUT
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_IDLE_TIMEOUT
        - name: DB_MAX_LIFETIME
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_MAX_LIFETIME
        - name: DB_AUTO_COMMIT
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_AUTO_COMMIT
        - name: DB_VALIDATION_TIMEOUT
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_VALIDATION_TIMEOUT
        - name: DB_LEAK_DETECTION_THRESHOLD
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_LEAK_DETECTION_THRESHOLD
        - name: DB_CACHE_PREP_STMTS
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_CACHE_PREP_STMTS
                    #- name: DB_JDBC_READ_TIMEOUT
                    # valueFrom:
                    #configMapKeyRef:
                    #name: my-configmap
                    #key: DB_JDBC_READ_TIMEOUT
        - name: DB_PREP_STMT_CACHE_SIZE
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_PREP_STMT_CACHE_SIZE
        - name: DB_PREP_STMT_CACHE_SQL_LIMIT
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_PREP_STMT_CACHE_SQL_LIMIT
        - name: DB_USE_LOCAL_SESSION_STATE
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_USE_LOCAL_SESSION_STATE
        - name: DB_REWRITE_BATCHED_STATEMENTS
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_REWRITE_BATCHED_STATEMENTS
        - name: DB_CACHE_RESULT_SET_METADATA
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_CACHE_RESULT_SET_METADATA
        - name: DB_CACHE_SERVER_CONFIGURATION
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_CACHE_SERVER_CONFIGURATION
        - name: DB_ELIDE_SET_AUTO_COMMITS
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_ELIDE_SET_AUTO_COMMITS
        - name: DB_MAINTAIN_TIME_STATS
          valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_MAINTAIN_TIME_STATS

 
---
apiVersion: v1
kind: Service
metadata:
  name: tms-service
spec:
  selector:
    app: tms-service
  ports:
    - protocol: TCP
      port: 8060
      targetPort: 8060
  type: ClusterIP

