apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  labels:
    app: transaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: quay.apps.ocphubho.neoleap.com.sa/ocpuat_softpos-sbs-sit/transaction-service:2.2.5-SNAPSHOT
          ports:
            - containerPort: 8070
          env:
            # - name: spring.jpa.properties.hibernate.entity-manager-factory-interface
            #  value: "jakarta.persistence.EntityManagerFactory"
            - name: VAULT_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: VAULT_TOKEN
            - name: VAULT_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: VAULT_ADDRESS
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: TRANSACTIONS_DB_URL
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_DRIVER_CLASS
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: TRANSACTIONS_DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: TRANSACTIONS_DB_PASSWORD
            - name: SPRING_JPA_SHOW_SQL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: HIBERNATE_SHOW_SQL
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: HIBERNATE_FORMAT_SQL
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: HIBERNATE_DDL_AUTO
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: HIBERNATE_DIALECT
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: TRANSACTIONS_DB_USERNAME
            - name: JAEGER_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: JAEGER_HOST
            - name: PAGE_SIZE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: PAGE_SIZE
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: RABBITMQ_PORT
# #new update
            - name: DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_TYPE
            - name: DB_CONNECTION_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_CONNECTION_TIMEOUT
            - name: DB_MINIMUM_IDLE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_MINIMUM_IDLE
            - name: DB_MAXIMUM_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_MAXIMUM_POOL_SIZE
            - name: DB_IDLE_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_IDLE_TIMEOUT
            - name: DB_MAX_LIFETIME
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_MAX_LIFETIME
            - name: DB_AUTO_COMMIT
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_AUTO_COMMIT
            - name: DB_VALIDATION_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_VALIDATION_TIMEOUT
            - name: DB_LEAK_DETECTION_THRESHOLD
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_LEAK_DETECTION_THRESHOLD
            - name: DB_CACHE_PREP_STMTS
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_CACHE_PREP_STMTS
                    #- name: DB_JDBC_READ_TIMEOUT
                    #valueFrom:
                    #configMapKeyRef:
                    #name: my-configmap
                    #key: DB_JDBC_READ_TIMEOUT
            - name: DB_PREP_STMT_CACHE_SIZE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_PREP_STMT_CACHE_SIZE
            - name: DB_PREP_STMT_CACHE_SQL_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_PREP_STMT_CACHE_SQL_LIMIT
            - name: DB_USE_LOCAL_SESSION_STATE
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_USE_LOCAL_SESSION_STATE
            - name: DB_REWRITE_BATCHED_STATEMENTS
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_REWRITE_BATCHED_STATEMENTS
            - name: DB_CACHE_RESULT_SET_METADATA
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_CACHE_RESULT_SET_METADATA
            - name: DB_CACHE_SERVER_CONFIGURATION
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_CACHE_SERVER_CONFIGURATION
            - name: DB_ELIDE_SET_AUTO_COMMITS
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_ELIDE_SET_AUTO_COMMITS
            - name: DB_MAINTAIN_TIME_STATS
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: DB_MAINTAIN_TIME_STATS
          volumeMounts:
          - name: my-log-pvc
            mountPath: "/log" 
      volumes:
      - name: my-log-pvc
        persistentVolumeClaim:
          claimName: my-log-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  type: NodePort
  ports:
    - port: 8070
      targetPort: 8070
      # nodePort: 30070  # Uncomment and change this port as needed
  selector:
    app: transaction-service



