apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-email-notification-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-email-notification-consumer
  template:
    metadata:
      labels:
        app: default-email-notification-consumer
    spec:
      containers:
      - name: default-email-notification-consumer
        image: default-route-openshift-image-registry.apps-crc.testing/default/default-email-notification-consumer:2.2.5-SNAPSHOT
        ports:
        - containerPort: 9062
        env:
        - name: SERVICE_PORT
          value: "9062"
        - name: JAEGER_HOST
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: JAEGER_HOST
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: RABBITMQ_HOST
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: RABBITMQ_PORT

---
apiVersion: v1
kind: Service
metadata:
  name: default-email-notification-consumer
spec:
  selector:
    app: default-email-notification-consumer
  ports:
    - protocol: TCP
      port: 9062
      targetPort: 9062
  type: ClusterIP
