apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyway-attestation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flyway-attestation
  template:
    metadata:
      labels:
        app: flyway-attestation
    spec:
      containers:
        - name: flyway-attestation
          image: flyway/flyway:latest
          command:
            - /flyway/flyway
            - -url=jdbc:oracle:thin:@//141.147.133.191:1521/FREE
            - -schemas=ATTESTATION
            - -user=ATTESTATION
            - -password=attestation
            - -connectRetries=10
            - -baselineOnMigrate=true
            - -createSchemas=false
            - migrate
          volumeMounts:
            - name: flywayattestation-config
              mountPath: /flyway/sql
      volumes:
        - name: flywayattestation-config
          configMap:
            name: flywayattestation-config  # Reference the ConfigMap for SQL files
